package main

var (
	ignoredFolders = map[string]bool{
		".git": true,
	}
	allowedExtensions = map[string]bool{
		".asp":        true,
		".aspx":       true,
		".c":          true,
		".cs":         true,
		".c++":        true,
		".cgi":        true,
		".cpp":        true,
		".css":        true,
		".csv":        true,
		".dtl":        true,
		".erb":        true,
		".go":         true,
		".h":          true,
		".hpp":        true,
		".hs":         true,
		".htm":        true,
		".html":       true,
		".hxx":        true,
		".hss":        true,
		".java":       true,
		".js":         true,
		".jsp":        true,
		".jspx":       true,
		".less":       true,
		".markdown":   true,
		".md":         true,
		".nim":        true,
		".php":        true,
		".php4":       true,
		".php5":       true,
		".pl":         true,
		".properties": true,
		".py":         true,
		".rb":         true,
		".rhtml":      true,
		".rss":        true,
		".scss":       true,
		".sass":       true,
		".shtml":      true,
		".svg":        true,
		".sql":        true,
		".txt":        true,
		".xml":        true,
		".xhtml":      true,
		".yaws":       true,
		".sh":         true,
		".bash":       true,
		".vb":         true,
		".swift":      true,
		".xlsx":       true,
		".pptx":       true,
	}
)
